version: '2'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "s3cr3t!"
      POSTGRES_DB: dev
    volumes:
      - ~/.ViewTheQueue/docker/postgres-data:/var/lib/postgresql/data
    networks:
      - dev-local
networks:
  dev-local:
    driver: bridge