spring:
  application:
    name: view-the-queue-service
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?searchpath=view_the_queue
    username: view_the_queue
    password: viewthequeue1
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: view_the_queue
    show-sql: false
  liquibase:
    default-schema: view_the_queue
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      base-path:
      exposure:
        include: '*'
---
spring:
  config:
    active:
      on-profile: test
  cloud:
    config:
      enabled: false
  liquibase:
    enabled: false